# Generated by Django 4.1.6 on 2023-02-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_alter_menuitem_options_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['quantity', 'unit_price']},
        ),
    ]
